### PR TITLE
Add Search Functionality with PDFKitten

### PR DESCRIPTION
**Pull request by jefflen**
Combines PDFKitten Library with Reader to add a search functionality.

Related to feature request #65

### CODE REVIEW

**Comment by jonezdotcom** [comment]
This is great!

**Comment by soulshined** [comment]
great work. some memory related issues for iPad but works great. thanks

**Comment by hugocroch** [comment]
Nice job by the way! But I have an issue with the search with the highlighting region. I searched for the reason, but I didn't find any clue. 

Here some example : When I write "Vacance", some results are well highlighted and some are not.
img_0057

Then, I saw a second issue but with accent character like "é" :  In this example, I wrote "congé"
img_0058

I guess this is probably the font used in my PDF or something like that.

**Comment by jefflen** [comment]
I think PDFKitten only supports PDF type-1 fonts. I got this issue as well for some documents. 

For this pull request I just use with PDFKitten but didn't modify any codes in it, there's another branch which described it but I think it's quite old.
https://github.com/KurtCode/PDFKitten/issues/18

Does anyone knows any PDFKitten branch that solved this or other libraries we can use?

**Comment by hugocroch** [comment]
Thanks for the answer. It seems that @tanis2000 has found a solution to support PDF type-2 font. Maybe, it will fix the issue for some PDF. Maybe if we try to implant the modification he made to the library, it is going to work?

**Comment by tanis2000** [comment]
@hugocroch this goes way back in time :)
You can add my changes https://github.com/slitskevich/PDFKitten/pull/1 but they're based off a different branch of PDFKitten as the original was way behind with fonts management and such. I can't say that adding my fixes will do the trick without also merging all of the patches made by @slitskevich

**Comment by hugocroch** [comment]
@tanis2000 Thanks for the info! I can give it a try even if I'm aware that adding your fixes could not work unless there is another solution.

**Comment by syrakozz** [comment]
+1

**Comment by hugocroch** [comment]
@tanis2000, just to inform you that I tried to merge the code and some workaround, but this is not quite a success.

**Comment by viezel** [comment]
I have also worked with Kitten, and I think the issue is in the ligature text parsing. My tests shows that "fi" "fl" and "ff" are not found by Kitten in Type1 strings. 
I did not find the solution, but think thats the issue for these incorrect text highlights

**Comment by feliciaf** [comment]
@jefflen you think i can still use this ?

**Comment by jefflen** [comment]
@feliciaf I did this push long time ago so not sure if it works now. But as long as it's still build I think you should be fine to use it.

**Comment by soulshined** [comment]
@feliciaf it's still in working order

**Comment by feliciaf** [comment]
@soulshined ok

**Comment by feliciaf** [comment]
@jefflen ok thanks

**Comment by feliciaf** [comment]
@jefflen  Awesome! viewed/pulled your new changes (PDFKitten) works great! downloaded cocoapods for the vfr reader.. would assume to incorporate this too ;)

**Comment by jefflen** [comment]
Cool!

**Pull request closed without merging**
